// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQXwA1MxCR2USn5UQ1Y9kPP2wLQoCx_U',
    appId: '1:197231827679:web:b056edb2ebc118093fe76a',
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    authDomain: 'authtutorial-cc98a.firebaseapp.com',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYuBGpW_hpV-GI5bk-X7949frbGjyq-Us',
    appId: '1:197231827679:android:c651630c6e3c837b3fe76a',
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzme638Y7T09NweatOPywjxOqUvRLOtY',
    appId: '1:197231827679:ios:9065ef5a5978dd6b3fe76a',
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzme638Y7T09NweatOPywjxOqUvRLOtY',
    appId: '1:197231827679:ios:9065ef5a5978dd6b3fe76a',
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQXwA1MxCR2USn5UQ1Y9kPP2wLQoCx_U',
    appId: '1:197231827679:web:f37cb595072952d63fe76a',
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    authDomain: 'authtutorial-cc98a.firebaseapp.com',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

}