// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_APIKEY']!,
    appId: dotenv.env['WEB_APPID']!,
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    authDomain: 'authtutorial-cc98a.firebaseapp.com',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['APK_APIKEY']!,
    appId: dotenv.env['APK_APPID']!,
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_APIKEY']!,
    appId: dotenv.env['IOS_APPID']!,
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MAC_APIKEY']!,
    appId: dotenv.env['MAC_APPID']!,
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WIN_APIKEY']!,
    appId: dotenv.env['WIN_APPID']!,
    messagingSenderId: '197231827679',
    projectId: 'authtutorial-cc98a',
    authDomain: 'authtutorial-cc98a.firebaseapp.com',
    storageBucket: 'authtutorial-cc98a.firebasestorage.app',
  );

}